(modifier) @keyword
(operator) @operator
(attribute) @attribute
(command_sync_prefix) @type
(punctuation) @punctuation.bracket
(delimiter) @punctuation.delimiter
(keysym) @variable
(comment) @comment
(range) @number
"\\\n" @punctuation.special
