[envs.default]
features = ["dev"]
dependencies = [
    "jinja2 < 3.1.0",
    "pytest >= 7.1.3, <8",
    "pytest-aiohttp >= 1.0.4, <2",
    "pytest-cov >= 2.12.1, <3",
    "syrupy >= 3.0.0, <4",
    "time-machine >= 2.6.0, <3",
]
[envs.default.scripts]
test = "pytest --cov-report term-missing --cov=textual tests/ -vv"
test-snapshot-update = "pytest --cov-report term-missing --cov=textual tests/ -vv --snapshot-update"
unit-test = 'pytest --cov-report term-missing --cov=textual tests/ -vv -m "not integration_test"'

[envs.lint]
detached = true
dependencies = [
    "black >= 22.3.0, <23",
    "mypy >= 0.982, <1",
    "pre-commit >= 2.12.1, <3",
]
[envs.lint.scripts]
format = "black src"
check = "black --check src"
typing = "mypy src/textual"

[envs.docs]
dependencies = [
    "mkdocs >= 1.3.0, <2",
    "mkdocs-material >= 8.2.15, <9",
    "mkdocstrings[python] >= 0.19.0, <1",
]
[envs.docs.scripts]
build = "mkdocs build"
deploy = "mkdocs gh-deploy"
serve = "mkdocs serve"
help = "mkdocs --help"
