from typing import Any


def log(*args: Any, verbosity: int = 0, **kwargs) -> None:
    from ._context import active_app

    app = active_app.get()
    app.log(*args, verbosity=verbosity, **kwargs)


def panic(*args: Any) -> None:
    from ._context import active_app

    app = active_app.get()
    app.panic(*args)

__explicit__ = ['panic', 'log']

# These attributes seem to be overloaded in submodules
__ignore__ = ['ActionError', 'Binding', 'Layout', 'log']


__autogen__ = """
This file is partially autogenerated by mkinit

To regenerate this file run:

    mkinit -m textual -w --lazy
    mkinit -m textual -w
"""


def lazy_import(module_name, submodules, submod_attrs):
    import importlib
    import os
    name_to_submod = {
        func: mod for mod, funcs in submod_attrs.items()
        for func in funcs
    }

    def __getattr__(name):
        if name in submodules:
            attr = importlib.import_module(
                '{module_name}.{name}'.format(
                    module_name=module_name, name=name)
            )
        elif name in name_to_submod:
            submodname = name_to_submod[name]
            module = importlib.import_module(
                '{module_name}.{submodname}'.format(
                    module_name=module_name, submodname=submodname)
            )
            attr = getattr(module, name)
        else:
            raise AttributeError(
                'No {module_name} attribute {name}'.format(
                    module_name=module_name, name=name))
        globals()[name] = attr
        return attr

    if os.environ.get('EAGER_IMPORT', ''):
        for name in name_to_submod.values():
            __getattr__(name)

        for attrs in submod_attrs.values():
            for attr in attrs:
                __getattr__(attr)
    return __getattr__


__getattr__ = lazy_import(
    __name__,
    submodules={
        'actions',
        'app',
        'background',
        'binding',
        'case',
        'driver',
        'drivers',
        'events',
        'geometry',
        'keys',
        'layout',
        'layout_map',
        'layouts',
        'message',
        'message_pump',
        'messages',
        'page',
        'reactive',
        'screen_update',
        'scrollbar',
        'view',
        'views',
        'widget',
        'widgets',
    },
    submod_attrs={
        'actions': [
            'parse',
            're_action_params',
        ],
        'app': [
            'App',
            'LayoutDefinition',
            'PLATFORM',
            'ViewType',
            'WINDOWS',
        ],
        'background': [
            'Background',
            'BackgroundRenderable',
        ],
        'binding': [
            'BindingStack',
            'Bindings',
            'NoBinding',
        ],
        'case': [
            'camel_to_snake',
        ],
        'driver': [
            'Driver',
        ],
        'events': [
            'Action',
            'Blur',
            'Callback',
            'Click',
            'DoubleClick',
            'Enter',
            'Event',
            'Focus',
            'Hide',
            'Idle',
            'InputEvent',
            'Key',
            'Leave',
            'Load',
            'Mount',
            'MouseCapture',
            'MouseDown',
            'MouseEvent',
            'MouseEventT',
            'MouseMove',
            'MouseRelease',
            'MouseScrollDown',
            'MouseScrollUp',
            'MouseUp',
            'Null',
            'Resize',
            'Show',
            'Shutdown',
            'ShutdownRequest',
            'Timer',
            'Unmount',
        ],
        'geometry': [
            'Offset',
            'Region',
            'Size',
            'Spacing',
            'SpacingDimensions',
            'T',
            'clamp',
        ],
        'keys': [
            'Keys',
        ],
        'layout': [
            'LayoutUpdate',
            'NoWidget',
            'OrderedRegion',
            'PY38',
            'ReflowResult',
            'WidgetPlacement',
        ],
        'layout_map': [
            'LayoutMap',
            'RenderRegion',
        ],
        'message': [
            'Message',
        ],
        'message_pump': [
            'CallbackError',
            'MessagePump',
            'MessagePumpClosed',
            'NoParent',
        ],
        'messages': [
            'CursorMove',
            'Update',
        ],
        'page': [
            'Page',
            'PageRender',
            'PageUpdate',
        ],
        'reactive': [
            'Reactive',
            'ReactiveType',
            'watch',
        ],
        'screen_update': [
            'ScreenUpdate',
        ],
        'scrollbar': [
            'ScrollBar',
            'ScrollBarRender',
            'ScrollDown',
            'ScrollLeft',
            'ScrollRight',
            'ScrollTo',
            'ScrollUp',
        ],
        'view': [
            'View',
        ],
        'widget': [
            'RenderCache',
            'Widget',
        ],
        'widgets': [
            'Button',
            'ButtonPressed',
            'DirectoryTree',
            'FileClick',
            'Footer',
            'Header',
            'NodeID',
            'Placeholder',
            'ScrollView',
            'Static',
            'TreeClick',
            'TreeControl',
            'TreeNode',
        ],
    },
)


def __dir__():
    return __all__

__all__ = ['Action', 'App', 'Background', 'BackgroundRenderable',
           'BindingStack', 'Bindings', 'Blur', 'Button', 'ButtonPressed',
           'Callback', 'CallbackError', 'Click', 'CursorMove', 'DirectoryTree',
           'DoubleClick', 'Driver', 'Enter', 'Event', 'FileClick', 'Focus',
           'Footer', 'Header', 'Hide', 'Idle', 'InputEvent', 'Key', 'Keys',
           'LayoutDefinition', 'LayoutMap', 'LayoutUpdate', 'Leave', 'Load',
           'Message', 'MessagePump', 'MessagePumpClosed', 'Mount',
           'MouseCapture', 'MouseDown', 'MouseEvent', 'MouseEventT',
           'MouseMove', 'MouseRelease', 'MouseScrollDown', 'MouseScrollUp',
           'MouseUp', 'NoBinding', 'NoParent', 'NoWidget', 'NodeID', 'Null',
           'Offset', 'OrderedRegion', 'PLATFORM', 'PY38', 'Page', 'PageRender',
           'PageUpdate', 'Placeholder', 'Reactive', 'ReactiveType',
           'ReflowResult', 'Region', 'RenderCache', 'RenderRegion', 'Resize',
           'ScreenUpdate', 'ScrollBar', 'ScrollBarRender', 'ScrollDown',
           'ScrollLeft', 'ScrollRight', 'ScrollTo', 'ScrollUp', 'ScrollView',
           'Show', 'Shutdown', 'ShutdownRequest', 'Size', 'Spacing',
           'SpacingDimensions', 'Static', 'T', 'Timer', 'TreeClick',
           'TreeControl', 'TreeNode', 'Unmount', 'Update', 'View', 'ViewType',
           'WINDOWS', 'Widget', 'WidgetPlacement', 'actions', 'app',
           'background', 'binding', 'camel_to_snake', 'case', 'clamp',
           'driver', 'drivers', 'events', 'geometry', 'keys', 'layout',
           'layout_map', 'layouts', 'log', 'message', 'message_pump',
           'messages', 'page', 'panic', 'parse', 're_action_params',
           'reactive', 'screen_update', 'scrollbar', 'view', 'views', 'watch',
           'widget', 'widgets']
