
name: Black format check

on:
  pull_request:
    paths:
      - '.github/workflows/black_format.yml'
      - '**.py'

jobs:
  black-format-check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.11
      - name: Install black
        run: python -m pip install black
      - name: Run black
        run: black --check src
